sudo: required

# branches:
#   only:
#     - master

services:
  - docker

script:
  - docker build -t guildtv/website:xposion-gfx-$TRAVIS_COMMIT .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push guildtv/website:xposion-gfx-$TRAVIS_COMMIT
  - echo "Deploying"