sudo: required

dotnet: 2.0.0-preview2
dist: trusty

services:
  - docker

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - ./build.sh $TRAVIS_BUILD_NUMBER
  - echo "Deploying"